# Generated by Django 4.2.6 on 2023-10-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherinfo',
            name='date_create',
        ),
    ]
